name: First Workflow
on:
  push:
    branches:
      - main
jobs:
  initial-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting message
        run: echo 'Welcome to the first GitHub Workflow.'
